/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#include "ble_stuff_list.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Stuff List packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Stuff List packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_STUFF_VALUE_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Stuff Value. */ 
#define MAX_STUFF_ENTRY_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Stuff Entry. */ 
#define MAX_STUFF_READED_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Stuff Readed. */ 
#define MAX_STUFF_NUMBER_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Stuff Number. */ 

/**@brief Function for encoding Stuff Value.
 *
 * @param[in]   p_stuff_value              Stuff Value characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t stuff_value_encode(ble_stuff_list_stuff_value_t * p_stuff_value, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_stuff_value->id, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for encoding Stuff Entry.
 *
 * @param[in]   p_stuff_entry              Stuff Entry characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t stuff_entry_encode(ble_stuff_list_stuff_entry_t * p_stuff_entry, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint16_encode(&p_stuff_entry->entry_number, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding Stuff Entry.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t stuff_entry_decode(uint8_t data_len, uint8_t * p_data, ble_stuff_list_stuff_entry_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint16_decode((data_len-pos), &p_data[pos], &p_write_val->entry_number); 

    return pos;
} 
/**@brief Function for encoding Stuff Readed.
 *
 * @param[in]   p_stuff_readed              Stuff Readed characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t stuff_readed_encode(ble_stuff_list_stuff_readed_t * p_stuff_readed, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_boolean_encode(&p_stuff_readed->all_readed, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding Stuff Readed.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t stuff_readed_decode(uint8_t data_len, uint8_t * p_data, ble_stuff_list_stuff_readed_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_boolean_decode((data_len-pos), &p_data[pos], &p_write_val->all_readed); 

    return pos;
} 
/**@brief Function for encoding Stuff Number.
 *
 * @param[in]   p_stuff_number              Stuff Number characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t stuff_number_encode(ble_stuff_list_stuff_number_t * p_stuff_number, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint16_encode(&p_stuff_number->entry_number, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_stuff_list       Stuff List Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_stuff_list_t * p_stuff_list, ble_evt_t * p_ble_evt)
{
    p_stuff_list->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_stuff_list       Stuff List Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_stuff_list_t * p_stuff_list, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_stuff_list->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_stuff_list       Stuff List Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_stuff_list_t * p_stuff_list, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_stuff_list->stuff_entry_handles.value_handle)
    {
        if(p_stuff_list->evt_handler != NULL)
        {
            ble_stuff_list_evt_t evt;
            evt.evt_type = BLE_STUFF_LIST_STUFF_ENTRY_EVT_WRITE;
            stuff_entry_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.stuff_entry);
            p_stuff_list->evt_handler(p_stuff_list, &evt);
        }
    }
    if(p_ble_evt->handle == p_stuff_list->stuff_readed_handles.value_handle)
    {
        if(p_stuff_list->evt_handler != NULL)
        {
            ble_stuff_list_evt_t evt;
            evt.evt_type = BLE_STUFF_LIST_STUFF_READED_EVT_WRITE;
            stuff_readed_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.stuff_readed);
            p_stuff_list->evt_handler(p_stuff_list, &evt);
        }
    }
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_stuff_list_t * p_stuff_list, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
            if (p_auth_req->request.write.handle == p_stuff_list->stuff_entry_handles.value_handle)
            {
                on_write(p_stuff_list, &p_auth_req->request.write);
            }
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_stuff_list       Stuff List Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_stuff_list_on_ble_evt(ble_stuff_list_t * p_stuff_list, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_stuff_list, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_stuff_list, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_stuff_list, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_stuff_list, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the Stuff List. */
uint32_t ble_stuff_list_init(ble_stuff_list_t * p_stuff_list, const ble_stuff_list_init_t * p_stuff_list_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_stuff_list->evt_handler = p_stuff_list_init->evt_handler;
    p_stuff_list->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x1A, 0xE7, 0xF5, 0x9D, 0xA2, 0x98, 0xBF, 0xBB, 0x89, 0x4A, 0xD9, 0x6E, 0x00, 0x00, 0x1A, 0xE7}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0xE71A;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_stuff_list->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Stuff Value characteristic
    ble_stuff_list_stuff_value_t stuff_value_initial_value = p_stuff_list_init->ble_stuff_list_stuff_value_initial_value; 

    uint8_t stuff_value_encoded_value[MAX_STUFF_VALUE_LEN];
    ble_add_char_params_t add_stuff_value_params;
    memset(&add_stuff_value_params, 0, sizeof(add_stuff_value_params));
    
    add_stuff_value_params.uuid                = 0xE71D;
    add_stuff_value_params.uuid_type           = ble_uuid.type; 
    add_stuff_value_params.max_len             = MAX_STUFF_VALUE_LEN;
    add_stuff_value_params.init_len            = stuff_value_encode(&stuff_value_initial_value, stuff_value_encoded_value);
    add_stuff_value_params.p_init_value        = stuff_value_encoded_value; 
    add_stuff_value_params.char_props.read     = 1; 
    add_stuff_value_params.read_access         = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_stuff_value_params.is_var_len          = 1; 

    err_code = characteristic_add(p_stuff_list->service_handle, &add_stuff_value_params, &(p_stuff_list->stuff_value_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Stuff Entry characteristic
    ble_stuff_list_stuff_entry_t stuff_entry_initial_value = p_stuff_list_init->ble_stuff_list_stuff_entry_initial_value; 

    uint8_t stuff_entry_encoded_value[MAX_STUFF_ENTRY_LEN];
    ble_add_char_params_t add_stuff_entry_params;
    memset(&add_stuff_entry_params, 0, sizeof(add_stuff_entry_params));
    
    add_stuff_entry_params.uuid                = 0xE71C;
    add_stuff_entry_params.uuid_type           = ble_uuid.type; 
    add_stuff_entry_params.max_len             = MAX_STUFF_ENTRY_LEN;
    add_stuff_entry_params.init_len            = stuff_entry_encode(&stuff_entry_initial_value, stuff_entry_encoded_value);
    add_stuff_entry_params.p_init_value        = stuff_entry_encoded_value; 
    add_stuff_entry_params.char_props.write    = 1; 
    add_stuff_entry_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_stuff_entry_params.is_var_len          = 1; 

    err_code = characteristic_add(p_stuff_list->service_handle, &add_stuff_entry_params, &(p_stuff_list->stuff_entry_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Stuff Readed characteristic
    ble_stuff_list_stuff_readed_t stuff_readed_initial_value = p_stuff_list_init->ble_stuff_list_stuff_readed_initial_value; 

    uint8_t stuff_readed_encoded_value[MAX_STUFF_READED_LEN];
    ble_add_char_params_t add_stuff_readed_params;
    memset(&add_stuff_readed_params, 0, sizeof(add_stuff_readed_params));
    
    add_stuff_readed_params.uuid                = 0xE71F;
    add_stuff_readed_params.uuid_type           = ble_uuid.type; 
    add_stuff_readed_params.max_len             = MAX_STUFF_READED_LEN;
    add_stuff_readed_params.init_len            = stuff_readed_encode(&stuff_readed_initial_value, stuff_readed_encoded_value);
    add_stuff_readed_params.p_init_value        = stuff_readed_encoded_value; 
    add_stuff_readed_params.char_props.write_wo_resp    = 1; 
    add_stuff_readed_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_stuff_readed_params.is_var_len          = 1; 

    err_code = characteristic_add(p_stuff_list->service_handle, &add_stuff_readed_params, &(p_stuff_list->stuff_readed_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Stuff Number characteristic
    ble_stuff_list_stuff_number_t stuff_number_initial_value = p_stuff_list_init->ble_stuff_list_stuff_number_initial_value; 

    uint8_t stuff_number_encoded_value[MAX_STUFF_NUMBER_LEN];
    ble_add_char_params_t add_stuff_number_params;
    memset(&add_stuff_number_params, 0, sizeof(add_stuff_number_params));
    
    add_stuff_number_params.uuid                = 0xE710;
    add_stuff_number_params.uuid_type           = ble_uuid.type; 
    add_stuff_number_params.max_len             = MAX_STUFF_NUMBER_LEN;
    add_stuff_number_params.init_len            = stuff_number_encode(&stuff_number_initial_value, stuff_number_encoded_value);
    add_stuff_number_params.p_init_value        = stuff_number_encoded_value; 
    add_stuff_number_params.char_props.read     = 1; 
    add_stuff_number_params.read_access         = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_stuff_number_params.is_var_len          = 1; 

    err_code = characteristic_add(p_stuff_list->service_handle, &add_stuff_number_params, &(p_stuff_list->stuff_number_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the Stuff Value. */
uint32_t ble_stuff_list_stuff_value_set(ble_stuff_list_t * p_stuff_list, ble_stuff_list_stuff_value_t * p_stuff_value)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_STUFF_VALUE_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = stuff_value_encode(p_stuff_value, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_stuff_list->conn_handle, p_stuff_list->stuff_value_handles.value_handle, &gatts_value);
}

/**@brief Function for setting the Stuff Number. */
uint32_t ble_stuff_list_stuff_number_set(ble_stuff_list_t * p_stuff_list, ble_stuff_list_stuff_number_t * p_stuff_number)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_STUFF_NUMBER_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = stuff_number_encode(p_stuff_number, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_stuff_list->conn_handle, p_stuff_list->stuff_number_handles.value_handle, &gatts_value);
}

